import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const version = readFileSync(join(root, "VERSION"), "utf8").trim();
if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`Invalid VERSION: ${version}`);
  process.exit(1);
}

const packagesDir = join(root, "packages");
for (const name of readdirSync(packagesDir)) {
  const pkgPath = join(packagesDir, name, "package.json");
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    if (pkg.version === version) continue;
    pkg.version = version;
    writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
    console.log(`synced ${name} → ${version}`);
  } catch (err) {
    if (err && typeof err === "object" && "code" in err && err.code === "ENOENT") continue;
    throw err;
  }
}

const versionTs = `/** Generated by scripts/sync-version.mjs — do not edit. */\nexport const VERSION = ${JSON.stringify(version)};\n`;
const versionTsPath = join(root, "packages/cli/src/version.ts");
writeFileSync(versionTsPath, versionTs, "utf8");
console.log(`wrote packages/cli/src/version.ts → ${version}`);
console.log(`VERSION=${version}`);
